version: '3.8'

services:
  picossg_node:
    image: node:lts
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
